[project]
name = "explorer_server"
version = "0.1.0"
description = "Download API for sdss/explorer"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy==1.26.4",
    "vaex==4.17.0",
]
